### ISSUE TITLE
Alt + Click does not jump

### ISSUE THREAD

**Issue by Arcesilas** [Gert-dev/php-integrator-navigation#14]
Hi,

So I have all working again after upgrading Atom :)

I've noticed a problem with Ctrl+Click (will open a new ticket), so I wanted to use Alt instead (not as convenient, but still good for me). It just does not work. The function function/method/whatever is underlined, but nothing happens when I click.

It's the only key not working. I've tried some combinations which all worked (Ctrl+Shift, even Alt+Shift).

**Comment by Gert-dev** [comment]
Do you happen to be using a Mac keyboard? I assumed the following mapping applies, but maybe I'm wrong:
* Control -> Control
* Option -> Alt
* Command -> Meta
* Shift -> Shift

**Comment by Arcesilas** [comment]
No, I'm on Linux with a very standard PC keyboard...

**Comment by Gert-dev** [comment]
Do you happen to be using GNOME? IIRC by default, GNOME maps the alt key to a "drag window" key. If you hold alt and then hold down the mouse on a window, does it allow you to move it around?

**Comment by Arcesilas** [comment]
Using Unity, and this shortcut is available too. But there is also a shortcut with "Super" key (meta) (which cannot be disabled) and Super+Click works... Even when the list of keyboad shortcut is displayed (keeping Meta pressed a long time).
But maybe both (Alt and Meta shortcuts in Unity) do not work the same way ?

There is also another shortcut, for HUD (Head-Up Display) whcih by default is "Alt", but changing the key binding does not change anything.

Anyway, for now, I use Alt + Shift. I think I'll get used to it after a while :)

**Comment by Gert-dev** [comment]
Ok, good to hear. Hopefully Atom will provide some means to disable the default behavior somewhere in the future (or provide a simple means to override it in certain cases).
