### ISSUE TITLE
Partly not doing Autocomplete

### ISSUE THREAD

**Issue by lukasoppermann** [Gert-dev/php-integrator-navigation#18]
Hey,

I have the following "issue". I have https://github.com/lukasoppermann/http-status installed as a package via composer.

What you can do, is implement an Interface which provides a ton of constants. If you implement this interface you can use `self::HTTP_OK`.

```php
use Lukasoppermann\Httpstatus\Httpstatuscodes;

class TestCase extends Laravel\Lumen\Testing\TestCase implements Httpstatuscodes
{
 ...
}
```

However the autocompletion does not work. `self::HTTP_` will not show any of the constants from the interface. I do not know of this is related, but `'HTT'` (as string in `'`) does show the correct names of the constants.

Is this desired behavior? Did I miss some kind of annotation or something? The https://github.com/tocjent/php-integrator-symbol-viewer does actually show the constants, which has me even more confused (if you select show inherited properties).

**Comment by Gert-dev** [comment]
Can you alt-click the Httpstatuscodes class and does it navigate to the correct file? I've tried including your library and implementing the interface and do get the expected result:

![schermafdruk van 2016-04-23 12-28-04](https://cloud.githubusercontent.com/assets/6823929/14760839/e5281d18-094e-11e6-87a0-e4f9affd8352.png)
![schermafdruk van 2016-04-23 12-28-26](https://cloud.githubusercontent.com/assets/6823929/14760840/e5299012-094e-11e6-879c-b60f59b438d3.png)

**Comment by lukasoppermann** [comment]
Sorry, you are correct, it was due to me using it within a testTrait, that does not implement the interface, but will have access when used within the test.
