### ISSUE TITLE
Not working after change branch

### ISSUE THREAD

**Issue by ALTELMA** [Gert-dev/php-integrator-navigation#21]
First time to use after install just ok, but while many minutes after I do stuff not work anymore until I re-install all plugins php-integrator-*.

Please suggestion or advice me to fix this problem.

**Comment by Gert-dev** [comment]
Hello

What operating system and version of Atom are you using? Do you have any other packages installed alongside the php-integrator packages? Is there anything listed in the console of the developer tools (e.g. Ctrl-Shift-I)?

Does it not work anymore as in:
* Nothing happens when you hover over an item while holding the alt key.
* A dashed line shows up and clicking doesn't do anything.
* A full line shows up and clicking doesn't do anything.

**Comment by ALTELMA** [comment]
Sorry for less information.
FYI : I use linux and I use only php-integrator-* a dashed line shows up and clicking doesn't do anything until I reinstall all again. This problem cause before install other plugin.

Thank you for reaponse.

**Comment by ALTELMA** [comment]
Sorry for less information.
FYI : I use linux and I use only php-integrator-* a dashed line shows up and clicking doesn't do anything until I reinstall all again. This problem cause before install other plugin.

Thank you for reaponse.

**Comment by Gert-dev** [comment]
Ok, does the dashed line show up on properties, methods or constants from classes or class names you happen to be modifying? Do your actions also involve copying existing class files, modifying the code and then renaming the class?

**Comment by ALTELMA** [comment]
I didn't change or rename filename / classname / method name 

This problem just cause with my friends. So I reccommended him to use it. 

I try to fix or how to sloved it by myself, because your plugins is cool and need to use it again.

**Comment by Gert-dev** [comment]
You mentioned the problem doesn't immediately occur, could you describe the steps you take for the problem to occur? If it only occurs in a specific code base, could you narrow it down to a small example (or, if this is not possible, is the code online somewhere)?

**Comment by ALTELMA** [comment]
Yes, the problem doesn't immediately occur. I think after change branch I see indexing file in project after that navigation cannot click and go to Mothod / Class forever until I remove all php-integrator-* all plugin and reinstall. It's work again I am not sure duration for not work again.

I don't change any code only switch branch.

**Comment by Gert-dev** [comment]
Alright, are the classes or methods that no longer work still exist before or after switching branches? In other words, is the class you are trying to switch to present in both branches or is it a new file that was added/renamed/relocated/... in one branch and not in the other?

**Comment by ALTELMA** [comment]
Maybe problem relates with sqlite version on desktop use 3.11.0
Do you think this is a problem?

I try to force indexing and not work.

**Comment by Gert-dev** [comment]
It could be, but everything above 3.7.11 _should_ be working correctly. Does force indexing not work in the sense that it still doesn't work or in that it shows an error message?

You could try commenting out the line here [1], though I doubt it will have any effect.

[1] https://github.com/Gert-dev/php-integrator-base/blob/master/php/src/IndexDatabase.php#L102

**Comment by Gert-dev** [comment]
Closing this due to its age. Let me know if this issue is still present or you experience any ohter issues, thanks!

**Comment by devarni** [comment]
It's broken here on Debian... the dashed line is clickable but that's all.
