### ISSUE TITLE
Symbols in the same namespace are not clickable

### ISSUE THREAD

**Issue by klausi** [Gert-dev/php-integrator-navigation#22]
Problem: if you refer to a class/interface in the same namespace you don't need a use statement in PHP. Unfortunately php-integrator does not seem to have support for this yet?

Example: Symfony's ContainerAwareInterface which refers to ContainerInterface in the type hint of a method: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ContainerAwareInterface.php

If I open this file I cannot click-navigate to ContainerInterface, although I should be able to.

**Comment by Gert-dev** [comment]
This should be working (or rather: it works here), has the project finished indexing and is anything else from php-integrator working (such as autocompletion, navigating to other classes besides this one, ...)?

**Comment by klausi** [comment]
Hm, strange, it is working now. Not sure what went wrong there, but thanks for answering!

**Comment by Gert-dev** [comment]
Good to hear!
