### ISSUE TITLE
Open files by symbol search

### ISSUE THREAD

**Issue by klausi** [Gert-dev/php-integrator-navigation#23]
Atom has this really useful fuzzy-finder:toggle-file-finder command to quickly open files by file name. Is there something similar for PHP symbols? Example: search for methods with the name "assertStringContains" and quickly open the file where the method is defined and jump to the declaration.

**Comment by Gert-dev** [comment]
Hello, there is the [php-integrator-symbol-viewer](https://github.com/tocjent/php-integrator-symbol-viewer) package by @tocjent that allows listing all symbols defined by classes in an open file. However, if I read your question correctly, it sounds as if you are looking more for a project-wide symbol search and not a search confined to the open file. It would certainly be possible to implement such a feature using the base service, as you can already fetch a list of all defined classes and fetch information about each of them. It would however require some time to calculate (just like the project fuzzy search does) as the list could be large. Once that's done, it can work mostly the same as the existing fuzzy file matching, except with symbols. It could be a nice addition to the symbol-viewer package, but it could also be implemented as a completely separate package.

(I deliberately pinged tocject so he might chip in.)

**Comment by tocjent** [comment]
@klausi @Gert-dev Seems like a great idea, although it does not really fit in php-integrator-symbol-viewer, I would prefer it to be a separate package. Currently I'm doing some experiments and research on using a framework for symbol-viewer view layer, so I'm not really available to do some investigation on searching by symbols, however I think it would be really fun to implement and useful.

Cheers,
tocjent

**Comment by Gert-dev** [comment]
I've added the idea to the README of the base package along with a link. I'll close this here as it's beyond the scope of any of the existing packages. I wish I could say I'll start a new package to implement this feature, but I have to be honest and admit that I already have my hands full with the current collection ;-). By putting it in the README, someone else may pick up on the idea and start a similar package.

**Comment by klausi** [comment]
So my workaround for now is to use the general project text search with Ctrl-Shift-F for now.
Looking for a class declaration? Type "s ContainerAware"
Looking for a method? Type "n assertContains("

That usually brings the search results down to a manageable size to quickly jump to declarations.

**Comment by Gert-dev** [comment]
Thanks for the info. I tend to give classes the same filename and only define one per file, that way the fuzzy project search (Ctrl+P by default, I think) works fairly well. It doesn't work for methods, however.
