### ISSUE TITLE
Alt+click send me to classes.php

### ISSUE THREAD

**Issue by fbourigault** [Gert-dev/php-integrator-navigation#24]
I'm using this package in a large Symfony project and sometimes the Alt+click send me to the app/cache/dev/classes.php file which just contains cached files from elsewhere in the project and as this file is very large (564KB, 19K+ lines), atom crashes.

I think the real file is indexed by php-integrator-base but the one from classes.php goes first. I think this should be handled in different ways:

- By implementing #20 
- By excluding app/cache from indexing (does php-integrator-base follow the atom Ignored Name setting?)

Thank you for all those amazing atom packages :)

**Comment by Gert-dev** [comment]
Thanks for the compliment! This is indeed currently an issue and your second item is already taken up in a base package ticket [1]. The next minor version of the base package will include project support and I hope to implement excluding folders sometime after that.

[1] https://github.com/Gert-dev/php-integrator-base/issues/113
